### ISSUE TITLE
subscription_grouping feature

### ISSUE THREAD

**Issue by mbobakov** [purpleidea/mgmt#10]
Hello.
I would like to propose grouping mechanism for a exported-collected 'resources'.
In my opinion, it must be looks like 'subscriptions' for the mgmt-instance.
Each instance might be run with optional parameter '--subscription'.  If parameter is empty the subscription == 'default'
Each 'exported resource' from client comes to clients subscription(if other subscription(s) is not specified in resource declaration).  

After it, 'collect' works in reverse way. It is not breaking change for your examples/graph3c.yaml but add more flexibility to mgmt.

If you have interest about it, I can write code and send PR to you. 

Feel free to discus about it. ;)

**Comment by purpleidea** [comment]
@mbobakov You'll have to explain a bit better what you're describing. I've already got a (not officially announced) "grouping" feature, so you might need to rename this, but if you'd like to explain more, I'd love to hear about it. Cheers!

**Comment by mbobakov** [comment]
@purpleidea, Let's just take a look at the examples:
Simple basic:
We are having 3-nodes. Two are with 'apache' subscription and one with 'nagios'
'apache'-nodes start with '--subscription apache' 
'nagios'-node starts with '--subscription nagios' 

configurations(apache[1|2] in graphs you must read as 'apache1' for first instance and 'apache2' for second):

**apache**
```
---
graph: apachegraph
types:
  file:
  - name: "@@monitor"
    path: "/tmp/nagiosmonitoredhosts/apache[1|2]"
    content: |
       i am monitor-config for a apache[1|2]
    state: exists
    export_to: nagios #<== Will be export to 'nagios' subscription

  - name: "@@knowhost" #<== Will be export to 'apache' subscription because mgmt runs with a '--subscription apache'
    path: "/tmp/knowapachies/apache[1|2]"
    content: |
      i am apache[1|2]
    state: exists
collect:
- type: file
  pattern: "/tmp/knowapachies/"
edges: []
```

**nagios**
```
---
graph: nagiosgraph
types:
  file:
  - name: "config"
    path: "/etc/monitoring/config.conf"
    content: |
      foo: 4
    state: exists
collect:
- type: file
  pattern: "/tmp/" # Will be collect only /tmp/nagiosmonitoredhosts/apache[1|2]  because mgmt runs with a '--subscription nagios'
edges: []
```

**State**
*apache-nodes*
```
tmp/knowapachies
     |- apache1
     `- apache2
tmp/nagiosmonitoredhosts is empty
```

*nagios-node*
```
tmp/knowapachies is empty
tmp/nagiosmonitoredhosts
     |- apache1
     `- apache2
```

I would like to hear your implementation of 'groupping'.
How you think, my idea is bad?
