### ISSUE TITLE
Improved YAML format

### ISSUE THREAD

**Issue by mildred** [purpleidea/mgmt#141]
Until we have the perfect DSL, I would suggest to improve the YAML format, and I have one idea for that:

```
version: 2
graph: mygraph
resources:
  - name: file1
    autoedge: true
    retry: -1
    # the presence of the file key denotes a file resource
    file:
      path: /tmp/mgmt/file1
      content: |
        Content of my file
      owner: root
  - name: docker
    # The presence of a svc key denotes a svc resource
    svc:
      state: running
      startup: enabled
    after: # list of resource it depends on, this create edges
      - file file1 # format: <resource kind><space><resource name>
    before: # list of resources that depends on this
      - noop checkpoint
  - name: checkpoint
    noop: true
edges:
  # additional edges just as before
```

The implementation of this (which I started) is even simpler because it doesn't need the reflect package in `yamlgraph/gconfig.go` in function `NewGraphFromConfig()`. The `resources` key already contains the list.

**Comment by roidelapluie** [comment]
I would rather propose:

```
  - name: file1
    autoedge: true
    retry: -1
    kind: file
    params:
      path: /tmp/mgmt/file1
      content: |
        Content of my file
      owner: root
    metaparams:
```
