### ISSUE TITLE
file: Should we support relative paths?

### ISSUE THREAD

**Issue by xiu** [purpleidea/mgmt#271]
See https://github.com/purpleidea/mgmt/pull/270#discussion_r153056822.

Since we're adding autoedges between file and exec for instance, we need to have the exact same reference on both sides to be sure it'll work.

Consider the following graph:
```yaml
---
graph: mygraph
resources:
  file:
  - name: file1
    path: "file"
    meta:
      autoedge: true
  exec:
  - name: exec1
    cmd: /home/vagrant/file
    meta:
      autoedge: true
    shell: ''
    timeout: 0
edges: []
```

Should we start mgmt in /home/vagrant, both resources would point to the same file and should have an autoedge between them.

One solution could be to apply filepath.Abs on all the paths that we put in FileUID, the other would be to simply refuse to validate when we don't have an absolute path in FileRes.
